// Where the WhatsApp "See lead" button lands: /l/<leadId>
//
// Short on purpose. Meta requires a dynamic template button's variable to be a
// URL SUFFIX, so the template holds
//   https://launchpad.theexpertsgroup.co.uk/l/{{1}}
// and each message supplies the lead id. Keeping the path to two characters
// leaves the most room for the id inside WhatsApp's URL display.
//
// THE CASE THIS EXISTS FOR: WhatsApp opens links in its OWN in-app browser,
// which has a separate cookie jar from Safari or Chrome. An agent who is signed
// in on their phone is NOT signed in there, so a tap arrives with no session.
// That's why simply redirecting the homepage wasn't enough — it only ever
// worked for someone already signed in inside that browser.
//
// So: signed in → straight to the lead. Not signed in → sign in, then the
// lead. Either way they end up in the same place, which is the point.

import { NextRequest, NextResponse } from "next/server";
import { SESSION_COOKIE } from "@/lib/auth";

export const dynamic = "force-dynamic";

/* Same forwarded-host handling as the Rex embed: behind Railway's proxy
   req.nextUrl.origin is the container's own address, which sends the browser
   to localhost. */
function originOf(req: NextRequest): string {
  const proto = req.headers.get("x-forwarded-proto")?.split(",")[0]?.trim();
  const host =
    req.headers.get("x-forwarded-host")?.split(",")[0]?.trim() ||
    req.headers.get("host")?.trim();
  return host ? `${proto || "https"}://${host}` : req.nextUrl.origin;
}

export async function GET(
  req: NextRequest,
  ctx: { params: Promise<{ id: string }> }
) {
  const { id } = await ctx.params;
  const origin = originOf(req);

  // Ids are generated by uid() — letters and digits. Anything else is someone
  // playing with the URL, and must not reach the redirect.
  const clean = /^[a-z0-9]{4,40}$/i.test(id) ? id : "";
  const target = clean
    ? `/dashboard/leads?lead=${encodeURIComponent(clean)}`
    : "/dashboard/leads";

  // No session in this browser — very common here, since WhatsApp's in-app
  // browser starts empty. Send them to sign in, carrying where they were
  // going so they land on the lead rather than a generic dashboard.
  if (!req.cookies.get(SESSION_COOKIE)?.value) {
    return NextResponse.redirect(
      new URL(`/login?next=${encodeURIComponent(target)}`, origin)
    );
  }

  return NextResponse.redirect(new URL(target, origin));
}
